-- ============================================================
-- 婚礼请柬数据库 · 在 Supabase 的 SQL Editor 里整段粘贴并运行一次即可
-- 包含：回执表、嘉宾表、站点内容表、云存储桶、权限与统计函数
-- （重复运行安全：全部用 if not exists / or replace）
-- ============================================================

-- ============================================================
-- ① 回执表
-- ============================================================
create table if not exists public.rsvp (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  attending boolean not null default true,
  guest_count int not null default 1 check (guest_count between 1 and 20),
  message text,
  needs_accommodation text not null default 'no',
  check_in_at text,
  check_out_at text,
  edit_token text,
  created_at timestamptz not null default now()
);

-- 老表补列（重复运行安全）
alter table public.rsvp add column if not exists guest_id bigint;
alter table public.rsvp add column if not exists needs_accommodation text not null default 'no';
alter table public.rsvp add column if not exists check_in_at text;
alter table public.rsvp add column if not exists check_out_at text;
alter table public.rsvp add column if not exists edit_token text;

-- ============================================================
-- ② 嘉宾表（编辑器管理，每人一个专属 token）
-- ============================================================
create table if not exists public.guests (
  id bigint generated by default as identity primary key,
  name text not null,
  token text not null unique,
  note text,
  created_at timestamptz not null default now()
);

-- ============================================================
-- ③ 站点内容表（编辑器写、请柬读，单行 id=1 的 jsonb）
-- ============================================================
create table if not exists public.site_settings (
  id int primary key,
  data jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

-- 先插一行空配置，编辑器直接 upsert
insert into public.site_settings (id, data)
values (1, '{}')
on conflict (id) do nothing;

-- ============================================================
-- ④ 行级安全（RLS）
-- ============================================================
alter table public.rsvp enable row level security;
alter table public.guests enable row level security;
alter table public.site_settings enable row level security;

-- 回执：宾客可提交（看不到别人的）；登录者（你）可查看/删除
create policy "宾客可提交回执" on public.rsvp
  for insert to anon with check (true);
create policy "管理员可查看回执" on public.rsvp
  for select to authenticated using (true);
create policy "管理员可删除回执" on public.rsvp
  for delete to authenticated using (true);

-- 嘉宾：只有登录者能管理（匿名不能直接读，防止名单泄露）
create policy "管理员管理嘉宾" on public.guests
  for all to authenticated using (true) with check (true);

-- 站点内容：任何人可读（请柬匿名读、编辑器登录读）、登录者可写
create policy "任何人可读内容" on public.site_settings
  for select using (true);
create policy "管理员可写内容" on public.site_settings
  for insert to authenticated with check (true);
create policy "管理员可改内容" on public.site_settings
  for update to authenticated using (true);

-- ============================================================
-- ⑤ 统计与查询函数
-- ============================================================

-- 公开统计：只返回数字，不泄露名单
create or replace function public.rsvp_count()
returns bigint
language sql
security definer
set search_path = public
as $$ select count(*) from public.rsvp $$;

grant execute on function public.rsvp_count() to anon, authenticated;

-- 专属邀请：凭 token 查自己的名字（匿名可用，但不暴露其他人）
create or replace function public.get_guest(p_token text)
returns table(id bigint, name text)
language sql
security definer
set search_path = public
as $$
  select id, name from public.guests where token = p_token
$$;

grant execute on function public.get_guest(text) to anon, authenticated;

-- 宾客修改自己的回执：凭提交时拿到的编辑凭证删除旧行
-- （不开放匿名直接 delete，防止误删别人的回执）
create or replace function public.delete_rsvp(p_id bigint, p_token text)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.rsvp where id = p_id and edit_token = p_token
$$;

grant execute on function public.delete_rsvp(bigint, text) to anon, authenticated;

-- ============================================================
-- ⑥ 山谷花园（宾客种花；公开可插入，总数公开统计）
-- ============================================================
create table if not exists public.garden (
  id bigint generated by default as identity primary key,
  flower_type text not null,
  message text,
  created_at timestamptz not null default now()
);

alter table public.garden enable row level security;

create policy "宾客可种花" on public.garden
  for insert to anon with check (true);

-- 公开统计：只返回数字，不泄露明细
create or replace function public.garden_count()
returns bigint
language sql
security definer
set search_path = public
as $$ select count(*) from public.garden $$;

grant execute on function public.garden_count() to anon, authenticated;

-- ============================================================
-- ⑦ 云存储桶（照片 / 音乐，公开可读，登录者可上传删除）
-- ============================================================
insert into storage.buckets (id, name, public)
values ('photos', 'photos', true), ('music', 'music', true)
on conflict (id) do nothing;

create policy "图片音乐公开可读" on storage.objects
  for select using (bucket_id in ('photos', 'music'));
create policy "管理员可上传" on storage.objects
  for insert to authenticated with check (bucket_id in ('photos', 'music'));
create policy "管理员可删除" on storage.objects
  for delete to authenticated using (bucket_id in ('photos', 'music'));
