-- ============================================================
-- 婚礼回执表 · 在 Supabase 的 SQL Editor 里整段粘贴并运行一次即可
-- ============================================================

-- 回执表
create table if not exists public.rsvp (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  attending boolean not null default true,
  guest_count int not null default 1 check (guest_count between 1 and 20),
  message text,
  created_at timestamptz not null default now()
);

-- 开启行级安全（默认谁都查不到）
alter table public.rsvp enable row level security;

-- 宾客可以提交回执（但不能看到别人的回执）
create policy "宾客可提交回执" on public.rsvp
  for insert to anon with check (true);

-- 只有登录的你（后台）可以查看和删除
create policy "管理员可查看" on public.rsvp
  for select to authenticated using (true);
create policy "管理员可删除" on public.rsvp
  for delete to authenticated using (true);

-- 公开统计函数：只返回数字，不泄露名单
create or replace function public.rsvp_count()
returns bigint
language sql
security definer
set search_path = public
as $$ select count(*) from public.rsvp $$;

grant execute on function public.rsvp_count() to anon, authenticated;
